/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponentMain {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMyComponentMainElement extends Components.MyComponentMain, HTMLStencilElement {
    }
    var HTMLMyComponentMainElement: {
        prototype: HTMLMyComponentMainElement;
        new (): HTMLMyComponentMainElement;
    };
    interface HTMLElementTagNameMap {
        "my-component-main": HTMLMyComponentMainElement;
    }
}
declare namespace LocalJSX {
    interface MyComponentMain {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "my-component-main": MyComponentMain;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component-main": LocalJSX.MyComponentMain & JSXBase.HTMLAttributes<HTMLMyComponentMainElement>;
        }
    }
}
